- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install  jdk, maven, git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven


    - name: Clone source code from github
      git:
        repo: 'https://github.com/moaf92/Webapp-Stack-Ansible.git'
        dest: ./project-repo
        version: main
      register: git_status


    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: project-repo
      when: git_status.changed
      register: mvn_info


    - name: Copy artifacts to files directory
      copy:
        src: "{{item}}"
        dest: files/ROOT.war
      with_fileglob: project-repo/target/*.war

    - name: Copy SQL file to files directory
      copy:
        src: project-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql
